USE [master]
GO
/****** Object:  Database [TestApi1]    Script Date: 24. 03. 2024 15:29:17 ******/
CREATE DATABASE [TestApi1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestApi1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TestApi1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestApi1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TestApi1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TestApi1] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestApi1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestApi1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestApi1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestApi1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestApi1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestApi1] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestApi1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestApi1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestApi1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestApi1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestApi1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestApi1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestApi1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestApi1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestApi1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestApi1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestApi1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestApi1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestApi1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestApi1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestApi1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestApi1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestApi1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestApi1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TestApi1] SET  MULTI_USER 
GO
ALTER DATABASE [TestApi1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestApi1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestApi1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestApi1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestApi1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TestApi1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TestApi1] SET QUERY_STORE = ON
GO
ALTER DATABASE [TestApi1] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [TestApi1]
GO
/****** Object:  User [test]    Script Date: 24. 03. 2024 15:29:17 ******/
CREATE USER [test] FOR LOGIN [test] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [test]
GO
ALTER ROLE [db_datareader] ADD MEMBER [test]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [test]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 24. 03. 2024 15:29:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[Id] [uniqueidentifier] NOT NULL,
	[ApiKey] [nvarchar](128) NOT NULL,
	[ClientName] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 24. 03. 2024 15:29:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[UserName] [nvarchar](32) NOT NULL,
	[FullName] [nvarchar](100) NULL,
	[EMail] [nvarchar](50) NULL,
	[MobilePhoneNumber] [nvarchar](50) NULL,
	[Language] [nvarchar](32) NOT NULL,
	[Culture] [nvarchar](10) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[ClientId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UniqueUserNameOnClient]    Script Date: 24. 03. 2024 15:29:17 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UniqueUserNameOnClient] ON [dbo].[Users]
(
	[UserName] ASC,
	[ClientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Clients] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([Id])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Clients]
GO
USE [master]
GO
ALTER DATABASE [TestApi1] SET  READ_WRITE 
GO

USE  [TestApi1]

INSERT INTO Clients( Id, ApiKey, ClientName) 
VALUES  
('617867E5-1B5F-45F4-8BDC-96A9109C3A27', '1AbecedA2Razreda3Klopi4Dni5Sinov6Kolov?', 'Osnova šola' ),
('B5B2C0D2-6F18-41AB-B6C0-4E8A361B0765', '100MuGromovaIJelenskihMiRogovaTakoMiChuluDedeVrachIBubnjevaDarkw00da!', 'Duh s sekiro' );

GO
